### ISSUE TITLE
Little help, please...

### ISSUE THREAD

**Issue by BiigAdy** [gdkchan/HDATextTool#1] opened 2016-08-24 22:23 UTC
Hello, so I've used the command "HDATextTool -xhda EVTMSG12.HDA EVTMSG12" and put BOY.HDA into HDATEXTTOOL Folder, but "cmd" doesn't reconize it.

**Comment by gdkchan** [comment] 2016-08-25 00:49
hello. which error message it shows? make sure that the tool exe file is on
the same folder of the hda file you want to extract, also make sure that
youre typing the same name of the exe. You can also try running it as
administrator (if youre using windows) to make sure that the program have
enough privilege to access the file.

Em 24/08/2016 7:23 PM, "BiigAdy" <notifications@github.com> escreveu:

**Comment by BiigAdy** [comment] 2016-08-26 05:48
Haven't found the exe file in HDATextTool folder... I've found HDATextTool.csproj file, put BOY.HDA in same folder, open it in cmd and it shows "HDATextTool" is not reconized as an internal or external command, operable program or batch file.

**Comment by BiigAdy** [comment] 2016-08-26 06:38
Hmm... I get error message like this ("HDATextTool -xhda EVTMSG12.HDA EVTMSG12" is not reconized as an internal or external command.) Didn't found the exe file. :( I don't know where its located. I've only found HDATextTool.csproj file in HDATextTool folder, and run it in cmd, and hda file is in the same folder as HDATextTool.csproj.

**Comment by BiigAdy** [comment] 2016-08-26 06:39
Hmm... I get error message like this ("HDATextTool -xhda EVTMSG12.HDA EVTMSG12" is not reconized as an internal or external command.) Didn't found the exe file. :( I don't know where its located. I've only found HDATextTool.csproj file in HDATextTool folder, and run it in cmd, and hda file is in the same folder as HDATextTool.csproj.

**Comment by gdkchan** [comment] 2016-08-26 11:41
Well there you have your problem. You need to compile it first to make the
program run. This is github, we're not supposed to upload binaries here
since the point is sharing the sources. Anyway I uploaded a exe here:
https://www.dropbox.com/s/yzdyo3p0k7ul1js/HDATextTool.zip?dl=0 You can use
it to unpack your files. In your case youll need to use hdatexttool -xhda
boy.hda

The instructions should have everything you need to know to use it.

**Comment by BiigAdy** [comment] 2016-08-26 20:28
Thank you very much!

**Comment by BiigAdy** [comment] 2016-08-26 20:28
Thank you very much!!

**Comment by BiigAdy** [comment] 2016-08-26 20:30
Thank you very much!

**Comment by BiigAdy** [comment] 2016-08-26 20:31
Thank you very much!!

**Comment by BiigAdy** [comment] 2016-08-26 20:31
Thank you very much!

**Comment by BiigAdy** [comment] 2016-08-26 20:40
Thank you very much, I appreciate your help, you are incredible!

**Comment by BiigAdy** [comment] 2016-08-26 20:41
Thank you very much!

**Comment by BiigAdy** [comment] 2016-08-26 20:44
Thank you very much!

**Comment by BiigAdy** [comment] 2016-08-26 20:46
Thank you very much, I appreciate your help, you'r incredible!

**Comment by BiigAdy** [comment] 2016-08-26 20:46
Thank you very much!

**Comment by BiigAdy** [comment] 2016-08-26 20:47
Thank you very much, I appreciate your help, you'r incredible!

**Comment by BiigAdy** [comment] 2016-08-26 20:48
Thank you very much, I appreciate your help, you'r incredible!

**Comment by BiigAdy** [comment] 2016-08-26 20:48
Thank you very much, I appreciate your help, you'r incredible!

**Comment by BiigAdy** [comment] 2016-08-26 20:49
Thank you very much, I appreciate your help, you'r incredible!

**Comment by BiigAdy** [comment] 2016-08-26 20:51
Thank you very much, I appreciate your help, you'r incredible!

**Comment by BiigAdy** [comment] 2016-08-26 20:52
Thank you very much, I appreciate your help, you'r incredible!

**Comment by BiigAdy** [comment] 2016-08-26 20:52
Thank you very much, I appreciate your help, you'r incredible!

**Comment by BiigAdy** [comment] 2016-08-26 20:54
Thank you very much, I appreciate your help, you'r incredible!

**Comment by BiigAdy** [comment] 2016-08-26 20:54
Thank you very much, I appreciate your help, you'r incredible!

**Comment by BiigAdy** [comment] 2016-08-26 22:37
Thank you very much!

**Comment by BiigAdy** [comment] 2016-09-09 14:53
Hmm... I've open the exe and got this.... ![issue](https://cloud.githubusercontent.com/assets/21228982/18391231/9bd1ea46-76ad-11e6-9bb4-92881472d257.png)

**Comment by BiigAdy** [comment] 2016-09-09 14:54
Hmm... I've opened exe and got this.... ![issue](https://cloud.githubusercontent.com/assets/21228982/18391366/1339ec0a-76ae-11e6-96bb-16b9dcc1ff7f.png)

**Comment by BiigAdy** [comment] 2016-10-04 21:30
I'm back. Was trying to open this file and won't work...

**Comment by BiigAdy** [comment] 2016-10-04 21:59
I'm back. Was trying to open this file and won't work. Do you have any solution for this? Otherwise i put it into "System32" folder and says as the shown in picture bellow.

**Comment by BiigAdy** [comment] 2016-10-04 21:59
I'm back. Was trying to open this file and won't work. Do you have any solution for this? Thanks

**Comment by BiigAdy** [comment] 2016-10-04 22:05
I'm back. Was trying to open this file and won't work. Do you have any solution for this? Otherwise i put it into "System32" folder and says as the shown in picture bellow.

**Comment by BiigAdy** [comment] 2016-10-04 22:28
I'm back. I was trying to open this file and it won't open.  Otherwise when I put it in "System32" Folder, it shows error like shown in the picture bellow. Do you have any solution for this? Thanks
![Uploading hdatexttool error.png…]()

**Comment by BiigAdy** [comment] 2016-10-04 22:36
I'm back. I was trying to open this file and it won't open.  Otherwise when I put it in "System32" Folder, it shows error like shown in the picture bellow. Do you have any solution for this? Thanks

**Comment by BiigAdy** [comment] 2016-10-04 22:39
I'm back. I was trying to open this file and it won't open.  Otherwise when I put it in "System32" Folder, it shows error like shown in the picture bellow. Do you have any solution for this? Thanks
![hdatexttool error](https://cloud.githubusercontent.com/assets/21228982/19095087/4cd1b63a-8a83-11e6-9112-9ad52c599f7a.png)

**Comment by gdkchan** [comment] 2016-10-04 22:43
you shouldn't place it on the System32 folder. About it not opening the file, you'll need to show the error it throws when you try to use the program normally (outside the sys32 folder). Also no need to close/open/close/open the issue, you only need to close it when the problem is resolved.

**Comment by BiigAdy** [comment] 2016-10-04 22:50
Aha. When I try to run it as Admin, it just closes, there's no error.

**Comment by BiigAdy** [comment] 2016-10-05 00:50
Do you know how to fix this problem?

**Comment by BiigAdy** [comment] 2016-10-05 01:03
I ment to say that when i try to open HDATextTool.exe it can't be open.

**Comment by BiigAdy** [comment] 2016-10-05 01:11
When i put it for ex. on Desktop it can't be run... I've try'ed to run it as Admin, but still the same. :(

**Comment by BiigAdy** [comment] 2016-10-05 04:51
Did you find anything? :)

**Comment by BiigAdy** [comment] 2016-10-05 20:42
Did you find how to fix his problem? :\

**Comment by BiigAdy** [comment] 2016-10-05 22:40
Sorry about this open/close the issue, while I'am on mobile phone and i reopen it accidentally.

**Comment by JamesCruz91** [comment] 2016-10-18 00:24
It doesn't work. :(

**Comment by skocko123** [comment] 2016-10-20 08:59
why it won't open?

**Comment by JamesCruz91** [comment] 2016-10-20 11:58
I was trying to open the program, and it does not show any error. it just can't open.

**Comment by BiigAdy** [comment] 2016-10-21 08:50
I figured it out. JamesCruz91, you should put in cmd.exe command like cmd /k then after that put the tool into same folder as cmd. Thanks alot for the program, gdkchan. You are amazing! :D

**Closed** 2016-10-22 13:29 UTC
